name: Build JS Protocol Docs

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4.0.0
    
      - name: Install jsdoc-to-markdown
        run: npm install -g jsdoc-to-markdown

      - name: Build JS Proto Docs
        run: ./bin/jsdocs.sh

      - name: Commit results to Github
        run: |
          git pull
          git config --local user.email "brendan@projectdiscovery.io" 
          git config --local user.name "olearycrew" 
          git commit -m "Update JS Protocol Docs (from GH Actions)" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

